
version: "3.8"
services:
  app:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - db
    links: 
      - redis # if app stops redis will stop too
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data-redis:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    container_name: redis-boilerplate
    restart: unless-stopped
    ports:
      - 6379:6379
volumes:
  db-data-redis: